---
# tasks file for pelorus-deploy
- python_requirements_info:
        dependencies:
          - openshift
          - requests

- name: Deployment of Pelorus core stack on OCP
  block:
  - name: Log in (obtain access token)
    k8s_auth:
      username: "{{ username }}"
      password: "{{ password }}"
    register: k8s_auth_results
  
  - name: Log in (obtain access token)
    ansible.builtin.shell: oc login -u "{{ username }}" -p "{{ password }}" "{{ api_url}}" --insecure-skip-tls-verify

  - name: Create {{ pelorus_project_name }} namespace
    k8s:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      name: "{{ pelorus_project_name }}"
      api_version: v1
      kind: Namespace
      state: present

  - name: Deploy latest version of Prometheus chart inside  (and create it)
    kubernetes.core.helm:
      name: operators
      chart_ref: /tmp/checkout/charts/operators
      release_namespace: "{{pelorus_project_name}}"
      create_namespace: true
      wait: true
      wait_timeout: 300s

  - name: Deploy latest version of Pelorus chart inside  (and create it)
    kubernetes.core.helm:
      name: pelorus
      chart_ref: /tmp/checkout/charts/pelorus
      release_namespace: "{{pelorus_project_name}}"
      create_namespace: true
      wait: true
      wait_timeout: 300s

  always:
  - name: If login succeeded, try to log out (revoke access token)
    when: k8s_auth_results.k8s_auth.api_key is defined
    k8s_auth:
      state: absent
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

