apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JHBxVFlQbkdERUcxUi9OZWlTdGc5bXVockFtdHBIQTlrbkF0LzVnNzB5N2JRby9zcTlLMW9pCg==
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque