---
# tasks file for pelorus-prereqs
- name: Install prerequisites
  block:
    
  - name: Install dependencies
    include: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}_package.yml"
      - "{{ ansible_distribution }}_package.yml"


  - name: Download Helm 3
    get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

  - name: Install Helm 3
    ansible.builtin.shell: /tmp/get_helm.sh >> /tmp/somelog.txt

  - name: Git checkout Pelorus repo
    ansible.builtin.git:
      repo: 'https://github.com/konveyor/pelorus.git'
      dest: /tmp/checkout

  - name: Download and unarchive OC client tool
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
      dest: /usr/local/bin
      remote_src: True
      keep_newer: true
    become: yes
    become_user: root
  
  - name: Install openshift and requests-oauthlib python package
    pip:
      name: ['requests-oauthlib', 'openshift']
      extra_args: --user

