- name: Install the latest version of openssl and jq on {{ansible_distribution}}
  yum:
    name: ['openssl','jq']
    state: latest
  become: yes
  become_user: root
  when:
    ansible_distribution == "RedHat"